name: Deploy on prod environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Service Account
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > ${HOME}/gcloud.json
          export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcloud.json"

      - name: Firebase Deploy
        run: firebase deploy --project the-note-1e04b --only hosting:the-note-1e04b
